BASE_GAME_NAME = "SANTA"
MAX_PLAYERS = 30
DEFAULT_MAX_PLAYERS = 10
MAX_GAMES = 5

MAX_PLAYERS_KEY = "Max players count"
GAME_NAME_KEY = "GameID"
GAME_PASSWORD_KEY = "Passkey"
GAME_INFO_KEY = "Game info"
